#!/usr/bin/env python3
"""Bootstrap gap_registry.toml from the canonical gap table in the living plan."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROW_RE = re.compile(
    r"^\|\s*(\d+)\s*\|\s*(.+?)\s*\|\s*(.+?)\s*\|\s*(.+?)\s*\|$"
)

HEADER_SKIP = re.compile(r"^[\|\-\s:]+$")


def parse_gaps(plan_text: str) -> list[dict]:
    gaps: dict[int, dict] = {}
    in_gap_section = False

    for line in plan_text.splitlines():
        if line.startswith("## Gap analysis"):
            in_gap_section = True
            continue
        if in_gap_section and line.startswith("## ") and "Gap analysis" not in line:
            # End of gap analysis major section — stop at next top-level section
            if not line.startswith("### Round"):
                break

        if not in_gap_section:
            continue

        m = ROW_RE.match(line)
        if not m:
            continue
        num = int(m.group(1))
        gap = m.group(2).strip()
        fix = m.group(3).strip()
        when = m.group(4).strip()
        if gap.lower() in ("gap", "gap / upgrade"):
            continue
        gaps[num] = {
            "id": num,
            "summary": gap,
            "fix": fix,
            "when": when,
        }

    ordered = [gaps[k] for k in sorted(gaps)]
    return ordered


def emit_toml(gaps: list[dict], source: str) -> str:
    lines = [
        "# Clan OS gap registry — canonical lifecycle tracking",
        "# Generated by scripts/import_gap_registry.py — review before scope-freeze",
        f'# source = "{source}"',
        "",
        "[schema]",
        'version = "1.0.0"',
        "status_values = [",
        '  "open",',
        '  "addressed",',
        '  "wontfix",',
        '  "split-into",',
        '  "superseded",',
        "]",
        "split_into_max_depth = 3",
        "",
        "# superseded: gap moot due to design decision (not wontfix risk acceptance)",
        "# superseded_by_commit must reference a commit touching DECISION_LOG or KERNEL_OBJECT_MODEL",
        "",
    ]
    for g in gaps:
        lines.extend(
            [
                "[[gaps]]",
                f'id = {g["id"]}',
                f'summary = """{g["summary"].replace(chr(34), chr(39))}"""',
                f'fix = """{g["fix"].replace(chr(34), chr(39))}"""',
                f'when = """{g["when"].replace(chr(34), chr(39))}"""',
                'status = "open"',
                "addressing_commit = null",
                "implementing_doc = null",
                "split_into = []",
                "superseded_by_commit = null",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--plan",
        type=Path,
        default=Path(__file__).resolve().parents[2]
        / ".cursor"
        / "plans"
        / "clanos_full_os_build_b960e4a0.plan.md",
        help="Path to living plan markdown",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "gap_registry.toml",
        help="Output gap_registry.toml path",
    )
    args = parser.parse_args()

    if not args.plan.exists():
        # Fallback: workspace-relative cursor plans path
        alt = Path.home() / ".cursor" / "plans" / "clanos_full_os_build_b960e4a0.plan.md"
        if alt.exists():
            args.plan = alt
        else:
            print(f"error: plan not found at {args.plan}", file=sys.stderr)
            return 1

    text = args.plan.read_text(encoding="utf-8")
    gaps = parse_gaps(text)
    if not gaps:
        print("error: no gaps parsed", file=sys.stderr)
        return 1

    out = emit_toml(gaps, str(args.plan))
    args.out.write_text(out, encoding="utf-8")
    print(f"wrote {len(gaps)} gaps to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
